---
- name: Letsencrypt | Reload nginx to activate the websites
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Letsencrypt | Install letsencrypt
  become: true
  community.general.snap:
    name: certbot
    classic: true
    state: present

- name: Letsencrypt | Link snap to /usr/bin
  become: true
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: Letsencrypt | Create letsencrypt certificate for {{ vpn_server_name }}
  become: true
  ansible.builtin.command: >
    certbot --nginx -m {{ vpn_webserver_email }}
    --agree-tos -d {{ vpn_server_name }}
    --noninteractive --redirect
  register: letsencrypt_resigned_certificate
  changed_when: letsencrypt_resigned_certificate.stdout == "0"

- name: Letsencrypt | Add Cronjob for Certificate Auto Renewal
  become: true
  ansible.builtin.cron:
    name: letsencrypt_renewal
    special_time: monthly
    job: "/usr/bin/certbot renew"
  when: ansible_facts['os_family'] == "Debian"

- name: Letsencrypt | Reload nginx to activate the websites
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Letsencrypt | Reboot the host
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 3600
