---
- name: Hardening Playbook
  hosts: wq_server
  gather_facts: true
  vars_files:
    - vars/local.yml

  roles:
    # - role: run_first
    # - role: fail2ban
    # - role: nginx_local
    # - role: letsencrypt
    # - role: docker
    - role: deploy
