---
- name: Deploy Local
  hosts: wg_server
  gather_facts: true
  vars_files:
    - vars/local.yml

  roles:
    - role: run_first
    - role: fail2ban
    - role: nginx
    - role: docker
    - role: deploy
