---
- name: Nginx | Ensure nginx is latest version
  become: true
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Nginx | Copy nginx config to server
  become: true
  ansible.builtin.template:
    src: "templates/{{ nginx_config_file }}"
    dest: /etc/nginx/sites-available/default
    owner: www-data
    group: www-data
    mode: '0644'

- name: Nginx | Create a folder for custom error pages
  become: true
  ansible.builtin.file:
    path: /etc/nginx/html
    state: directory
    mode: '0644'

- name: Nginx | Create symbolic link for nginx enabled sites
  become: true
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: Nginx | Allow all access to tcp port 80
  community.general.ufw:
    rule: allow
    name: "Nginx HTTP"
  become: true

- name: Nginx | Allow all access to tcp port 443
  community.general.ufw:
    rule: allow
    name: "Nginx HTTPS"
  become: true

- name: Nginx | Start nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
