---
- name: Ensure that wireguard is in acceptable state
  ansible.builtin.include_tasks:
    file: check-wireguard.yml

- name: Format wireguard conf file with facts from deploy
  ansible.builtin.include_tasks:
    file: setup-wireguard-conf.yml

- name: Ready docker-compose file
  ansible.builtin.include_tasks:
    file: setup-compose.yml

- name: Bring down service, update and bring back up
  ansible.builtin.include_tasks:
    file: setup-docker-images.yml

- name: Start Wireguard server
  become: true
  ansible.builtin.service:
    name: wg-quick@wg0.service
    enabled: true
    state: restarted

- name: Setup command pipe for BE service
  ansible.builtin.include_tasks:
    file: setup-command-pipe.yml

- name: Align BE's server peers to host
  ansible.builtin.include_tasks:
    file: align-server-peers.yml

- name: Print out new WG_VPN_REGISTRATION_TOKEN variable
  ansible.builtin.debug:
    msg: >
      New VPN Registration token is:
      >>>>>>>>>>> {{ vpn_registration_token.stdout }} <<<<<<<<<<<

      (To persist this token, set VPN_ROTATE_REGISTRATION_TOKEN=False in your deploy)
  when: vpn_rotate_registration_token

- name: Print out persisted WG_VPN_REGISTRATION_TOKEN variable
  ansible.builtin.debug:
    msg: >
      Reused VPN Registration token:
      >>>>>>>>>>> {{ vpn_registration_token.stdout }} <<<<<<<<<<<
  when: vpn_rotate_registration_token
