---
- name: Generate wireguard server token, and read into var
  ansible.builtin.shell:
    cmd: set -o pipefail && tr -dc A-Za-z0-9 </dev/urandom | head -c 25; echo ''
    executable: /bin/bash
  register: vpn_registration_token
  changed_when: true

- name: Read remote Public key into var
  become: true
  ansible.builtin.slurp:
    src: /etc/wireguard/public.key
  register: public_key

- name: Copy over Backend Docker-compose file
  become: true
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: /home/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
