---
- name: Generate wireguard registration token, and read into var
  ansible.builtin.shell:
    cmd: set -o pipefail && tr -dc A-Za-z0-9 </dev/urandom | head -c 25; echo ''
    executable: /bin/bash
  register: vpn_registration_token
  changed_when: true
  when: vpn_rotate_registration_token

- name: Persist wireguard registration token, and read into var
  ansible.builtin.shell:
    cmd: set -o pipefail && grep "WG_VPN_REGISTRATION_TOKEN=" /home/docker-compose.yml | awk -F "=" '{print $2}'
    executable: /bin/bash
  register: vpn_registration_token
  changed_when: true
  when: not vpn_rotate_registration_token

- name: Read remote Public key into var
  become: true
  ansible.builtin.slurp:
    src: /etc/wireguard/public.key
  register: public_key

- name: Copy over Backend Docker-compose file
  become: true
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: /home/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
