---
- name: Setup Wireguard config | Read remote Private key into var
  become: true
  ansible.builtin.slurp:
    src: /etc/wireguard/private.key
  register: private_key

- name: Setup Wireguard config | Copy Wireguard config file to server
  become: true
  ansible.builtin.template:
    src: templates/wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0040'

- name: Setup Wireguard config | Set and reload System-control IPv4 forwarding
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
