---
- name: Conclude Setup | Disable password logins
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: Conclude Setup | Restart ssh
  become: true
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Conclude Setup | Confirm snap is correctly installed
  become: true
  community.general.snap:
    name: core
    channel: latest/stable

- name: Conclude Setup | Set timezone variables
  become: true
  community.general.timezone:
    name: Africa/Johannesburg
