---
- name: Install Prerequisites
  become: true
  ansible.builtin.apt:
    name: aptitude
    update_cache: true
    force_apt_get: true

- name: Update apt and install default packages
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install required system packages
  become: true
  ansible.builtin.apt:
    name: "{{ sys_packages }}"
