---
- name: Conclude default packages | Install Prerequisites
  become: true
  ansible.builtin.apt:
    name: aptitude
    update_cache: true
    force_apt_get: true

- name: Conclude default packages | Update apt and install default packages
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Conclude default packages | Install required system packages
  become: true
  ansible.builtin.apt:
    name: "{{ sys_packages }}"
