---
- name: Install docker | Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install docker | Upgrade all apt packages
  ansible.builtin.apt:
    upgrade: dist
  become: true

- name: Install docker | Install system dependencies
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg-agent

- name: Install docker | Add an apt signing key for Docker
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install docker | Add apt repository for stable version
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker | Install Docker
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Install docker | Install Docker-Compose
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - docker-compose

- name: Install docker | Create config folder for doctl
  become: true
  ansible.builtin.file:
    path: /root/.config
    state: directory
    mode: "0644"

- name: Install docker | Install doctl (used to auth with Digital Ocean)
  become: true
  community.general.snap:
    name: doctl

- name: Install docker | Connect doctl with docker
  become: true
  ansible.builtin.command: snap connect doctl:dot-docker
  register: docker_connect_doct
  changed_when: docker_connect_doct.stdout == "0"
